---
- name: Module - kernel_support_info
  hosts: localhost
  gather_facts: true
  vars:
    access_token: "{{ lookup('file', '/tmp/falcon_token.json') }}"
  tasks:
    - name: Show support info using kernel and architecture from ansible_facts
      crowdstrike.falcon.kernel_support_info:
        filter: "release:'{{ ansible_facts['kernel'] }}'+architecture:'{{ ansible_facts['architecture'] }}'"

    # - name: Show support info for all Ubuntu 20 kernels that have a release starting with 5.8
    #  crowdstrike.falcon.kernel_support_info:
    #    auth: "{{ access_token }}"
    #    filter: "vendor:'ubuntu'+distro:'ubuntu20'+release:*'5.8.*'"

    # - name: Give me all kernels supported for Amazon Linux
    #  crowdstrike.falcon.kernel_support_info:
    #    auth: "{{ access_token }}"
    #    filter: "vendor:'ubuntu'"
    #  register: kernel_support

    # - name: Use Ansible to refine results - show top 5 most recent kernels for x86_64
    #  ansible.builtin.debug:
    #    var: (kernel_support.info | selectattr('architecture', 'equalto', 'x86_64') | sort(true, attribute='created_timestamp'))[:5]
