---
- name: Example of working with Falcon detections
  hosts: all
  sources:
    - crowdstrike.falcon.eventstream:
        falcon_client_id: "{{ FALCON_CLIENT_ID }}"
        falcon_client_secret: "{{ FALCON_CLIENT_SECRET }}"
        falcon_cloud: "us-2"
        stream_name: "YOUR_ALIAS-example"
        include_event_types:
          - "DetectionSummaryEvent"

  rules:
    - name: Host contain demo
      condition: event.falcon.event.ComputerName is match('YOUR_ALIAS') and event.falcon.event.Severity > 3
      action:
        run_playbook:
          name: playbooks/host_contain.yml
          extra_vars:
            computer_name: "{{ event.falcon.event.ComputerName }}"
            detection_description: "{{ event.falcon.event.DetectDescription }}"
            host_id: "{{ event.falcon.event.SensorId }}"
            detection_id: "{{ event.falcon.event.DetectId }}"
            detection_url: "{{ event.falcon.event.FalconHostLink }}"
